---
# tasks

- name: Install iptables rules saver
  apt:
    name: iptables-persistent
    state: present
    update_cache: yes

- name: Copy iptables rules
  template:
    src: "{{ iptables_script }}.j2"
    dest: "/tmp/{{ iptables_script }}"
    mode: 0550

- name: Apply iptables rules
  shell: "/tmp/{{ iptables_script }}"
  ignore_errors: yes

- name: enable and start iptable saver
  shell: "mkdir /etc/iptables; iptables-save > /etc/iptables/rules.v4"

- name: copy iptable restauration script
  copy:
    src: "{{ iptables_restore_script }}"
    dest: /etc/network/if-up.d/iptables
    mode: 0744
