---

- name: Disable firewall service
  service:
    name: firewalld
    enabled: no
    state: stopped
  when: ansible_distribution == "Fedora"

- name: Install iptables deps
  yum:
    name: [libselinux-python, iptables-services]
    state: present

- name: enable iptables saver service
  service:
    name: iptables
    enabled: yes
    state: started

- name: Copy iptables rules
  template:
    src: "{{ iptables_script }}.j2"
    dest: "/tmp/{{ iptables_script }}"
    mode: 0550

- name: Apply iptables rules
  shell: "/tmp/{{ iptables_script }}"
  ignore_errors: yes

- name: save iptables rules
  shell: "service iptables save"
