---

- name: install deps
  apt:
    name: sudo
    state: present
    update_cache: yes
    dpkg_options: 'force-confask,force-confnew,force-confmiss'
  when: ansible_os_family == "Debian"

- name: change root password
  user:
    name: root
    password: "{{ root_pwd | password_hash('sha512') }}"
  become: yes

- name: Make sure we have a 'sudo' group
  group:
    name: sudo
    state: present
  tags: user

- name: add ssh user
  user:
    name: "{{ ssh_user_name }}"
    password: "{{ ssh_user_pwd | password_hash('sha512') }}"
    groups: sudo
    shell: /bin/bash
    state: present
    create_home: yes
  tags: user

- name: Allow sudo group
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo  ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'
  tags: user

- name: Ensures {{ ssh_user_name }} ssh dir exists
  file:
    path: "/home/{{ ssh_user_name }}/.ssh"
    state: directory

- name: move root authorized_keys to user authorized_keys
  copy:
    src: "/root/.ssh/authorized_keys"
    dest: "/home/{{ ssh_user_name }}/.ssh/"
    remote_src: yes
    mode: 0600
    owner: "{{ ssh_user_name }}"
    group: "{{ ssh_user_name }}"
  tags: user

- name: Change ssh port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Port"
    line: "Port {{ ssh_port }}"
    state: present
  tags: ssh

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  tags: ssh

- name: Use public key authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
    state: present
  tags: ssh

- name: Limit Users’ ssh access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    line: "AllowUsers {{ ssh_user_name }}"
    state: present
  tags: ssh

- name: Disable Empty Passwords
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
    state: present
  tags: ssh

- name: Disable .rhosts files
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^IgnoreRhosts"
    line: "IgnoreRhosts yes"
    state: present
  tags: ssh

- name: Disable host-based authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^HostbasedAuthentication"
    line: "HostbasedAuthentication no"
    state: present
  tags: ssh

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  tags: ssh

- name: Restart SSH
  service: name=ssh state=restarted
  when: ansible_os_family == "Debian"

- name: Restart SSH
  service: name=sshd state=restarted
  when: ansible_os_family == "RedHat"

- name: Generate configuration in ssh config file
  # multiline is not working :/
  shell: "{{ role_path }}/files/gen_ssh_config.sh {{ inventory_hostname }} {{ hostvars[inventory_hostname].ansible_host }} {{ ssh_user_name }} {{ ssh_port }}"
  delegate_to: localhost
  tags:
    - dbg

