---
# tasks file for roles/vps-ssh

- name: Set OS dependent variables
  include_vars: '{{ item }}'
  ignore_errors: true
  with_first_found:
   - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
   - '{{ ansible_distribution }}.yml'
   - '{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml'
   - '{{ ansible_os_family }}.yml'
  tags: always

- name: Unminimize image
  block:
    - name: copy unminimize script
      copy:
        src: ubuntu-unminimize.sh
        dest: /usr/local/sbin/unminimize
        mode: 0775
    - name: unminimize image
      shell: unminimize
  when: ansible_distribution == "Ubuntu" and inventory_hostname in groups['scw']
  tags: min

- name: Set hostname
  hostname: name={{ inventory_hostname }}
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  tags: hostname

- name: Ensure persistent hostname
  lineinfile:
    dest=/etc/hostname
    line="{{ ansible_hostname }}"
  tags: hostname

- name: include ssh setup tasks
  include_tasks: ssh.yml
  tags: ssh

# XXX: Hack to restart ssh without loosing connection
- name: Restart sshd
  service:
    name={{ sshd_service_name }}
    state=restarted
  async: 1
  poll: 0

- name: Override ansible user/port after setting up sshd
  set_fact:
    ansible_port: "{{ ssh_server_port }}"
    ansible_user: "{{ ssh_user_name }}"

- block:
  - name: include firewall setup tasks
    include_tasks: firewall.yml

  - name: include Fail2ban setup tasks
    include_tasks: fail2ban.yml
    tags: fail2ban
  become: True
