---
# tasks file for ssh

- name: change root password
  user:
    name: root
    password: "{{ root_pwd | password_hash('sha512') }}"
  become: yes

- name: Make sure we have a 'sudo' group
  group:
    name: sudo
    state: present
  tags: user

- name: add ssh user
  user:
    name: "{{ ssh_user_name }}"
    password: "{{ ssh_user_pwd | password_hash('sha512') }}"
    groups: sudo
    shell: /bin/bash
    state: present
    create_home: yes
  tags: user

- name: Allow sudo group
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo  ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'
  tags: user

- name: Ensures {{ ssh_user_name }} ssh dir exists
  file:
    path: "/home/{{ ssh_user_name }}/.ssh"
    state: directory
  tags: user

- name: move root authorized_keys to user authorized_keys
  copy:
    src: "/root/.ssh/authorized_keys"
    dest: "/home/{{ ssh_user_name }}/.ssh/"
    remote_src: yes
    mode: 0600
    owner: "{{ ssh_user_name }}"
    group: "{{ ssh_user_name }}"
  tags: user

- name: get openssh-version
  shell: ssh -V 2>&1 | sed -r 's/.*_([0-9]*\.[0-9]).*/\1/g'
  args:
    executable: /bin/sh
  changed_when: false
  register: sshd_version
  check_mode: no
  tags: ssh

- name: include tasks to create crypo-vars
  include_tasks: crypto.yml
  tags: ssh

- name: create revoked_keys and set permissions to root/600
  template:
    src: 'revoked_keys.j2'
    dest: '/etc/ssh/revoked_keys'
    mode: '0600'
    owner: '{{ ssh_owner }}'
    group: '{{ ssh_group }}'
  tags: ssh

- name: create sshd_config and set permissions to root/600
  template:
    src: 'opensshd.conf.j2'
    dest: '/etc/ssh/sshd_config'
    mode: '0600'
    owner: '{{ ssh_owner }}'
    group: '{{ ssh_group }}'
    validate: '/usr/sbin/sshd -T -f %s'
  tags: ssh

- name: Update .ssh/config file
  shell: >
    {{ role_path }}/files/gen_ssh_config.sh {{ inventory_hostname }}
    {{ hostvars[inventory_hostname].ansible_host }} {{ ssh_user_name }}
    {{ ssh_server_port }}
  when: ssh_update_config_file
  delegate_to: localhost
  become: false
  tags: ssh
