---

- name: Setup docker compose as systemd service
  hosts: docker
  gather_facts: yes
  vars:
    - ansible_python_interpreter: "/usr/bin/env python3"
    - ansible_become: yes
  roles:
    - role: docker-compose
