---

- name: Setup a target VPS with my personal secure configuration
  hosts: vps
  gather_facts: no # done below
  vars_prompt:
    - name: root_pwd
      prompt: "Provide root password"
      private: yes
      confirm: yes
      when: root_pwd is null
    - name: ssh_user_pwd
      prompt: "Provide ssh user password"
      confirm: yes
      when: ssh_user_pwd is null
  pre_tasks:
    - raw: >
        test -e $(which python3) ||
        (yum -y update && yum install -y wget gcc openssl-devel bzip2-devel &&
        wget -P /tmp https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz &&
        tar -C /usr/src -xzf /tmp/Python-3.7.2.tgz &&
        pushd /usr/src/Python-3.7.2 &&
        ./configure --enable-optimizations &&
        make altinstall &&
        ln -s /usr/local/bin/python3.7 /usr/local/bin/python3)
      ignore_errors: true
    - name: Gathering Facts
      setup:
      tags: always
  vars:
    - ansible_python_interpreter: "/usr/bin/env python3"
    - ansible_user: root
    - ansible_port: 22
  roles:
    - role: vps-init #vps-hardening
