---

- name: Setup a target VPS with my personal secure configuration
  hosts: vps
  gather_facts: no # done below
  vars_prompt:
    - name: root_pwd
      prompt: "Provide root password"
      private: yes
      confirm: yes
      when: root_pwd is null
    - name: ssh_user_name
      prompt: "Provide ssh user name"
      private: no
      when: ssh_user_name is null
    - name: ssh_user_pwd
      prompt: "Provide ssh user password"
      confirm: yes
      when: ssh_user_pwd is null
  pre_tasks:
    - raw: >
        test -e /usr/bin/python3.7 ||
        (yum -y update && yum install gcc openssl-devel bzip2-devel &&
        wget -P /usr/src https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz &&
        tar xzf /usr/src/Python-3.7.2.tgz &&
        pushd /usr/src &&
        ./configure --enable-optimizations &&
        make altinstall)
      ignore_errors: true
    - name: Gathering Facts
      setup:
      tags: always
  vars:
    - ansible_python_interpreter: "/usr/bin/env python3"
    - ansible_user: root
    - ansible_port: 22
  roles:
    - role: vps-init #vps-hardening
