---

- name: Setup multipoint VPN between all VPS
  hosts: wireguard-vpc
  gather_facts: yes
  vars:
    - ansible_python_interpreter: "/usr/bin/env python3"
    - ansible_become: yes
  roles:
    - role: wireguard-vpc
